; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:yoradio-esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36/platform-espressif32.zip
board = esp32s3devkitc1_n16r8
framework = arduino
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions.csv
board_build.filesystem = littlefs

upload_resetmethod = esp32r0
build_type = release
lib_archive = no

;platform_packages =
;    tool-mklittlefs4 @ https://github.com/pioarduino/registry/releases/download/0.0.1/mklittlefs-4.0.2.zip

build_flags =
  ; === Уровень логирования ESP-IDF ===
  ; Ставим 2 (WARN) вместо 3 (INFO), чтобы видеть только важные сообщения,
  ; а не весь информационный шум. Загрузочные логи (##[BOOT]#) идут через Serial.print()
  ; и видны независимо от этого уровня.
  -DCORE_DEBUG_LEVEL=3
  -DCONFIG_ARDUHAL_LOG_COLORS=1 
  -DARDUINO_RUNNING_CORE=1
  -DAUDIOTASK_CORE=0
  -DAUDIOCONTROLTASK_PRIO=15
  -DBOARD_HAS_PSRAM=1
  -DCONFIG_SPIRAM_SUPPORT=1
  -DCONFIG_ASYNC_TCP_RUNNING_CORE=0
  -DCONFIG_ASYNC_TCP_USE_WDT=0
  -DWS_MAX_QUEUED_MESSAGES=128
  -DCONFIG_ASYNC_TCP_QUEUE_LEN=64
  -DCONFIG_ASYNC_TCP_PRIORITY=10
  ; --- НАСТРОЙКИ USB/UART ДЛЯ ОТЛАДКИ ---
  ; Если вы используете обычный DevKit и подключены к порту UART (через чип CP2102/CH340), 
  ; то ARDUINO_USB_CDC_ON_BOOT должен быть равен 0, чтобы лог шел в UART.
  ; Если вы подключены к нативному USB порту ESP32-S3, то ставьте 1.

  ; [DevKit]:
   -DARDUINO_USB_MODE=0
   -DARDUINO_USB_CDC_ON_BOOT=0
  
  ; [JC4827W543543 для отладки через UART порт]:
  ;-DARDUINO_USB_MODE=1      ; 0 - использовать режим OTG, 1 - режим JTAG+CDC
  ;-DARDUINO_USB_CDC_ON_BOOT=1 ; 0 - вывод Serial в UART (стандарт), 1 - перенаправить в USB CDC (Native)
  
  -DARDUINO_USB_MSC_ON_BOOT=0
  -DARDUINO_USB_DFU_ON_BOOT=0

monitor_speed = 115200
;monitor_filters = esp32_exception_decoder, log2file, time
monitor_filters = esp32_exception_decoder, time
upload_speed = 921600

upload_protocol = esptool
lib_deps = 
	https://github.com/moononournation/Arduino_GFX.git
	bblanchon/ArduinoJson @ ^7.2.1
	adafruit/Adafruit GFX Library
	adafruit/Adafruit ILI9341
  bodmer/TJpg_Decoder @ ^1.0.6



